export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "./globals.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-7xl mx-auto mt-10 ">{children}</div>
      </body>
    </html>
  );
}
